# Generated by Django 3.2.3 on 2021-05-29 22:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sugoi', '0002_auto_20210530_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
